"""
Generate exclude_calls.sql from an Excel file of authorized call IDs.

Usage:
    python execution/generate_exclude_calls_sql.py <path_to_xlsx>

Example:
    python execution/generate_exclude_calls_sql.py "C:/Users/keset/Downloads/callBook1.xlsx"

Output:
    execution/exclude_calls.sql  — run this on the server via:
        docker compose exec -T postgres psql -U postgres -d cora < exclude_calls.sql
"""
from __future__ import annotations

import sys
from pathlib import Path

try:
    import openpyxl
except ImportError:
    print("ERROR: openpyxl not installed. Run: pip install openpyxl")
    sys.exit(1)


def load_call_ids(xlsx_path: str) -> list[str]:
    wb = openpyxl.load_workbook(xlsx_path, read_only=True, data_only=True)
    ws = wb.active
    ids: list[str] = []
    for row in ws.iter_rows(min_row=2, values_only=True):  # skip header row
        val = row[0]
        if val and str(val).strip():
            ids.append(str(val).strip())
    wb.close()
    return ids


def generate_sql(call_ids: list[str]) -> str:
    quoted = ",\n    ".join(f"'{cid}'" for cid in call_ids)
    return f"""\
-- Generated by execution/generate_exclude_calls_sql.py
-- Marks call_events from the week of 2026-04-13 that are NOT in the
-- authorized list as report_excluded = TRUE.
--
-- Authorized call IDs: {len(call_ids)}
-- Run with:
--   docker compose exec -T postgres psql -U postgres -d cora < exclude_calls.sql

BEGIN;

UPDATE call_events
SET report_excluded = TRUE
WHERE created_at >= '2026-04-13 00:00:00+00'
  AND created_at <  '2026-04-20 00:00:00+00'
  AND call_id NOT IN (
    {quoted}
  );

-- Verify before committing
SELECT
  COUNT(*) FILTER (WHERE NOT report_excluded) AS counted,
  COUNT(*) FILTER (WHERE report_excluded)     AS excluded,
  COUNT(*)                                    AS total
FROM call_events
WHERE created_at >= '2026-04-13'
  AND created_at <  '2026-04-20';

COMMIT;
"""


def main() -> None:
    if len(sys.argv) < 2:
        print("Usage: python execution/generate_exclude_calls_sql.py <path_to_xlsx>")
        sys.exit(1)

    xlsx_path = sys.argv[1]
    call_ids = load_call_ids(xlsx_path)
    print(f"Loaded {len(call_ids)} call IDs from {xlsx_path}")

    out_path = Path(__file__).parent / "exclude_calls.sql"
    out_path.write_text(generate_sql(call_ids), encoding="utf-8")
    print(f"SQL written to: {out_path}")
    print()
    print("Next steps:")
    print(f"  1. Copy to server:  scp {out_path} root@<server-ip>:/opt/cora-recap-engine/")
    print("  2. Run on server:   docker compose exec -T postgres psql -U postgres -d cora < exclude_calls.sql")


if __name__ == "__main__":
    main()
