-- =============================================================================
-- monitor_queries.sql — Live monitoring queries for production simulation
-- =============================================================================
-- Replace <contact_id> with the actual value (e.g., 'sim-sc1-001').
-- Replace <call_id> with the actual call_id from the webhook payload.
-- All queries target Postgres.
-- =============================================================================


-- ---------------------------------------------------------------------------
-- LEAD STATE
-- ---------------------------------------------------------------------------

-- Current state for a specific contact
SELECT contact_id, campaign_name, ai_campaign_value, status,
       do_not_call, next_action_at, version, updated_at
FROM lead_state
WHERE contact_id = '<contact_id>';

-- All simulation contacts at a glance
SELECT contact_id, campaign_name, ai_campaign_value, status,
       do_not_call, next_action_at, updated_at
FROM lead_state
WHERE contact_id LIKE 'sim-sc%'
ORDER BY contact_id;

-- Leads that changed state in the last 5 minutes
SELECT contact_id, campaign_name, ai_campaign_value, status, updated_at
FROM lead_state
WHERE updated_at >= NOW() - INTERVAL '5 minutes'
ORDER BY updated_at DESC;


-- ---------------------------------------------------------------------------
-- SCHEDULED JOBS
-- ---------------------------------------------------------------------------

-- All jobs for a contact (any status)
SELECT job_type, status, run_at,
       payload_json->>'contact_id' AS contact_id,
       payload_json->>'campaign_name' AS campaign,
       payload_json->>'vm_retry_attempt' AS attempt,
       created_at
FROM scheduled_jobs
WHERE payload_json->>'contact_id' = '<contact_id>'
ORDER BY created_at DESC;

-- Pending jobs for a contact
SELECT id, job_type, status, run_at,
       payload_json->>'contact_id' AS contact_id
FROM scheduled_jobs
WHERE payload_json->>'contact_id' = '<contact_id>'
  AND status IN ('pending', 'claimed', 'running')
ORDER BY run_at ASC;

-- All simulation jobs in the last 10 minutes
SELECT job_type, status, run_at,
       payload_json->>'contact_id' AS contact_id,
       created_at
FROM scheduled_jobs
WHERE payload_json->>'contact_id' LIKE 'sim-sc%'
  AND created_at >= NOW() - INTERVAL '10 minutes'
ORDER BY created_at DESC;

-- Failed jobs (recent)
SELECT id, job_type, entity_id, status, updated_at,
       payload_json->>'contact_id' AS contact_id
FROM scheduled_jobs
WHERE status = 'failed'
  AND updated_at >= NOW() - INTERVAL '30 minutes'
ORDER BY updated_at DESC;

-- Pending outbound calls (retry queue)
SELECT id, job_type, run_at,
       payload_json->>'contact_id' AS contact_id,
       payload_json->>'phone_number' AS phone,
       payload_json->>'vm_retry_attempt' AS attempt,
       payload_json->>'campaign_name' AS campaign
FROM scheduled_jobs
WHERE job_type = 'launch_outbound_call'
  AND status = 'pending'
ORDER BY run_at ASC;


-- ---------------------------------------------------------------------------
-- CALL EVENTS
-- ---------------------------------------------------------------------------

-- Call events for a contact
SELECT call_id, status, duration_seconds,
       LEFT(transcript, 120) AS transcript_preview,
       created_at
FROM call_events
WHERE contact_id = '<contact_id>'
ORDER BY created_at DESC;

-- Call events for a specific call_id (dedupe check)
SELECT id, call_id, contact_id, status, dedupe_key, created_at
FROM call_events
WHERE call_id = '<call_id>';

-- Recent call events (all simulation contacts)
SELECT call_id, contact_id, status,
       LEFT(transcript, 80) AS transcript_preview,
       created_at
FROM call_events
WHERE contact_id LIKE 'sim-sc%'
ORDER BY created_at DESC
LIMIT 20;


-- ---------------------------------------------------------------------------
-- EXCEPTIONS
-- ---------------------------------------------------------------------------

-- Open exceptions
SELECT id, type, severity, entity_type, entity_id,
       context_json, created_at
FROM exceptions
WHERE status = 'open'
ORDER BY severity DESC, created_at DESC;

-- Exceptions for a contact
SELECT id, type, severity, status, context_json, created_at
FROM exceptions
WHERE entity_id = '<contact_id>'
ORDER BY created_at DESC;

-- All simulation exceptions
SELECT type, severity, status, entity_id, created_at
FROM exceptions
WHERE entity_id LIKE 'sim-sc%'
ORDER BY created_at DESC;


-- ---------------------------------------------------------------------------
-- OUTBOUND / INBOUND MESSAGES
-- ---------------------------------------------------------------------------

-- Outbound messages for a contact (SMS/email generated by worker)
SELECT channel, status, LEFT(body, 80) AS body_preview, created_at
FROM outbound_messages
WHERE contact_id = '<contact_id>'
ORDER BY created_at DESC;

-- Inbound messages (replies) for a contact
SELECT channel, LEFT(body, 80) AS body_preview, received_at
FROM inbound_messages
WHERE contact_id = '<contact_id>'
ORDER BY received_at DESC;

-- Pending SMS/email jobs
SELECT job_type, status, run_at,
       payload_json->>'contact_id' AS contact_id,
       payload_json->>'attempt_number' AS attempt
FROM scheduled_jobs
WHERE job_type IN ('send_sms', 'send_email')
  AND status IN ('pending', 'claimed', 'running')
ORDER BY run_at ASC;
